name: Test Build

on:
  push:
  workflow_dispatch:

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ".output/public"
